import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, Header } from "@/components/shared";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/provider";

const netflix = localFont({
  src: [
    {
      path: "./styles/fonts/Netflix-Sans-Bold.otf",
      weight: "700",
    },
    {
      path: "./styles/fonts/Netflix-Sans-Light.otf",
      weight: "400",
    },
    {
      path: "./styles/fonts/Netflix-Sans-Medium.otf",
      weight: "600",
    },
  ],
  variable: "--font-netflix",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${netflix.variable} `}>
        <Toaster />
        <Header />
        <Provider>{children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
